In [2]:
import numpy as np

In [12]:
np.array([1,5,66]).shape

(3,)

In [4]:
np.array([1,5,66])

array([ 1,  5, 66])

In [15]:
np.zeros(5).dtype

dtype('float64')

In [17]:
y = np.array([[[1,2,3],[4,5,6]] , [[2,3,4], [5,6,7]]])

In [19]:
y.shape

(2, 2, 3)

In [21]:
y[0,1,1]

5

In [24]:
y.T

array([[[1, 2],
        [4, 5]],

       [[2, 3],
        [5, 6]],

       [[3, 4],
        [6, 7]]])

In [48]:
x = np.array([[3,3,3], [1,3,4] , [7,1,3]])

In [52]:
len(set(x.flatten()))

4

In [21]:
ones = np.ones(5)
two = np.full(5,2)
np.dot(ones, two)

10.0

In [42]:
foo = np.array([[0,9,19,13],[1,20,5,13],[12,11,3,4]])
bar = np.array([[2,0,0,0],[1,2,2,0],[2,1,1,0],[0,0,1,1]])
foobar = np.dot(foo,bar)
foobar

array([[47, 37, 50, 13],
       [32, 45, 58, 13],
       [41, 25, 29,  4]])

In [45]:
dim = min(len(foobar), len(foobar[0]))
print(foobar[np.arange(dim), np.arange(dim)])

[47 45 29]


In [58]:
b = np.array([[-1, 33, 4, 1], [0, 1, 1, 0]])
print(b)

[[-1 33  4  1]
 [ 0  1  1  0]]


In [59]:
np.mean(b)

4.875

### SciPy

#### Является ли данная система векторов линейно независимой [6, 0, 3], [0, -1, 2], [12, 3, 0]? - Да! т.к. det == 0

In [1]:
from scipy import linalg

In [13]:
x , y, z = [6, 0, 3], [0, -1, 2], [12, 3, 0]

In [14]:
a = np.array([x,y,z])
linalg.det(a)

0.0

#### Найти собственные числа матрицы

In [15]:
a = np.array([[1, -1, -1, 0], [-1, 2, -1, -1], [-1,-1,2,-1], [0,-1,-1,1]])
print(a)

[[ 1 -1 -1  0]
 [-1  2 -1 -1]
 [-1 -1  2 -1]
 [ 0 -1 -1  1]]


In [18]:
print(linalg.eig(a)[0])

[-1.+0.j  1.+0.j  3.+0.j  3.+0.j]


#### Найти обратную матрицу и след обратной матрицы (сумма элементов главной диагонали)

In [20]:
a = np.array([[2,4,0,4,1],[2,4,1,1,0],[1,1,1,2,2],[0,1,3,2,4],[2,2,2,0,2]])

In [23]:
a1 = linalg.inv(a)
a1

array([[-0.6 ,  0.4 ,  1.6 , -0.6 , -0.1 ],
       [ 0.9 , -0.6 , -1.9 ,  0.4 ,  0.65],
       [-1.7 ,  1.8 ,  2.7 , -0.2 , -1.45],
       [-0.7 ,  0.8 ,  1.7 , -0.2 , -0.95],
       [ 1.4 , -1.6 , -2.4 ,  0.4 ,  1.4 ]])

In [25]:
dim = min(len(a1), len(a1[0]))
print(sum(a1[np.arange(dim), np.arange(dim)]))

2.7
